### ISSUE TITLE
dev: Build on Linux

### ISSUE THREAD

**Issue by monkey-w1n5t0n** [lnfiniteMonkeys/uSEQ#20]
The entire module (minus the Arduino-specific bits) should be buildable, testable, and most importantly debug-able on x64 (mostly Linux for now).

Some progress has been made on the [separate-interpreter branch](https://github.com/lnfiniteMonkeys/uSEQ/tree/separate-interpreter).

Tasklist:
TBD

**Comment by chriskiefer** [comment]
fixed with the virtual interface
